= morsed
:toc: left
:sectnums:

image:https://github.com/jiro4989/morsed/workflows/test/badge.svg[test]
image:https://codecov.io/gh/jiro4989/morsed/branch/master/graph/badge.svg[codecov,link="https://codecov.io/gh/jiro4989/morsed"]

morsedは品詞を指定して文字列を置換するコマンドです。

== Usage

基本的な使い方は以下。

[source,bash]
----
$ morsed -p 名詞 -s 寿司 吾輩は猫である。名前はまだない
寿司は寿司である。寿司はまだない

# 標準入力からも入力可能
$ morsed -p 名詞 -s 寿司 < README.adoc
----

検索パラメータを複数指定した場合はAND条件で絞り込まれます。

[source,bash]
----
$ morsed -p 名詞 -s 寿司 彼彼女田中
寿司寿司寿司

$ morsed -p 名詞 --part2 代名詞 -s 寿司 彼彼女田中
寿司寿司田中

$ morsed -p 名詞 --part2 代名詞 -r カレ -s 寿司 彼彼女田中
寿司彼女田中
----

検索パラメータには正規表現が使えます。

[source,bash]
----
$ morsed -r 'カ.*' -s 寿司 彼彼女田中
寿司寿司田中
----

== Help

`morsed -h`

 morsed morphological analyzer sed.
 Copyright (c) 2020 jiro4989
 Released under the Apache License version 2.0.
 https://github.com/jiro4989/morsed
 
 Options:
       --surface str          surface
       --baseform str         baseform 基本形
       --conjugationform str  conjugationform 活用形
       --conjugationtype str  conjugationtype 活用型
   -p, --part str             part of speech level 1 品詞再分類1
       --part2 str            part of speech level 2 品詞再分類2
       --part3 str            part of speech level 3 品詞再分類3
       --part4 str            part of speech level 4 品詞再分類4
       --pronunciation str    pronunciation 発音
   -r, --reading str          reading 読み
   -s, --sub str              substring
   -P, --print                print tokens
   -j, --json                 json format for printing (need --print)
       --pretty               pretty print json (need --print and --json)
   -h, --help

== License

Apache License 2.0
