name: test

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'

env:
  graalvm-version: '20.2.0'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: lein deps
      - run: lein cloverage --codecov
      - uses: codecov/codecov-action@v1

  test-native-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install GraalVM
        run: |
          cd /tmp
          if ! [ -d /tmp/graalvm-ce-java11-${{ env.graalvm-version }} ]; then
            curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-${{ env.graalvm-version }}/graalvm-ce-java11-linux-amd64-${{ env.graalvm-version }}.tar.gz

            tar xzf graalvm-ce-java11-linux-amd64-${{ env.graalvm-version }}.tar.gz
          fi
      - name: Build native image
        run: |
          export GRAALVM_HOME=/tmp/graalvm-ce-java11-${{ env.graalvm-version }}
          $GRAALVM_HOME/bin/gu install native-image
          lein uberjar
          $GRAALVM_HOME/bin/native-image \
            -jar target/morsed.jar \
            -H:Name=morsed \
            -H:+ReportExceptionStackTraces \
            -J-Dclojure.spec.skip-macros=true \
            -J-Dclojure.compiler.direct-linking=true \
            "-H:IncludeResources=command.edn" \
            "-H:IncludeResources=schema.edn" \
            "-H:IncludeResources=config.edn" \
            "-H:IncludeResources=version.txt" \
            "-H:IncludeResources=docs.adoc" \
            '-H:IncludeResources=.*/.*.bin$' \
            --initialize-at-build-time  \
            --report-unsupported-elements-at-runtime \
            -H:Log=registerResource: \
            --verbose \
            --no-fallback \
            --no-server \
            --static \
            "-J-Xmx3g"
          ls -lah

      - name: Run command
        run: |
          ./morsed
          ./morsed -p 名詞 -s 寿司 吾輩は猫である。
