name: test

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'

env:
  app-name: 'morsed'
  graalvm-download-url-prefix: 'https://github.com/graalvm/graalvm-ce-builds/releases/download'
  graalvm-version: '20.2.0'

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: lein deps
      - run: lein cloverage --codecov
      - uses: codecov/codecov-action@v1

  test-native-image:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            os: linux
            cmd: gu
          - runs-on: macOS-latest
            os: darwin
            cmd: gu
          - runs-on: windows-latest
            os: windows
            cmd: gu.cmd
    steps:
      - uses: actions/checkout@v2

      - uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: '20.2.0.java11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          # To use Clojure CLI 1.10.1.561 based on tools.deps
          cli: '1.10.1.469'
          # leiningen and boot-cli can be installed as well
          lein: 2.9.4
          # For leiningen and boot you could use 'latest' version
          boot: latest

      - name: Build native image
        run: |
          $GRAALVM_HOME/bin/${{ matrix.cmd }} install native-image
          lein uberjar
          $GRAALVM_HOME/bin/native-image \
            -jar target/${{ env.app-name }}.jar \
            -H:Name=${{ env.app-name }} \
            -H:+ReportExceptionStackTraces \
            -J-Dclojure.spec.skip-macros=true \
            -J-Dclojure.compiler.direct-linking=true \
            "-H:IncludeResources=command.edn" \
            "-H:IncludeResources=schema.edn" \
            "-H:IncludeResources=config.edn" \
            "-H:IncludeResources=version.txt" \
            "-H:IncludeResources=docs.adoc" \
            '-H:IncludeResources=.*/.*.bin$' \
            --initialize-at-build-time  \
            --report-unsupported-elements-at-runtime \
            -H:Log=registerResource: \
            --verbose \
            --no-fallback \
            --no-server \
            --static \
            "-J-Xmx3g"
          ls -lah

      - name: Run command
        run: |
          ./${{ env.app-name }}
          ./${{ env.app-name }} -p 名詞 -s 寿司 吾輩は猫である。
